#######################
# niminit config file #
# (c) Sangelo - 2023  #
#######################
[general]
# Should compatibility warnings be suppressed?
suppressWarnings = false

[project]
# This is the directory inside your home folder containing all of your templates.
sourceDirectory = "/.config/niminit/templates"
# The directory to be created inside the project, and to copy the selected project template into. (for example: utils)
targetDirectory = ".vscode"
# The default template to use when not explicitly specified. (for example: java)
defaultTemplate = "nim"